<?php
namespace Easy_MCP_AI\Tools\Blocks;

use Easy_MCP_AI\Tools\Base_Tool;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Update_Post_Blocks extends Base_Tool {

    use Block_Tree;

    const OPS = array( 'set_attributes', 'replace', 'insert', 'remove' );
    const AT  = array( 'before', 'after', 'append', 'prepend' );

    
    const DELIMITER_ONLY_ATTRIBUTES = array( 'metadata', 'lock' );

    public function get_name() {
        return 'wp_update_post_blocks';
    }

    public function get_description() {
        return 'Edits individual Gutenberg blocks inside a post, page or custom post type item without rewriting the whole content. Read the tree with `wp_get_post_blocks` first to get paths. Required: `post_id`, `ops` (array of operations, applied in order). Optional: `post_type` (REST base, default `posts`), `dry_run` (validate and report without saving). Each op: `op` = `set_attributes` (merge `attrs` into the block\'s delimiter attributes; a null value deletes a key; only the comment JSON changes. On a block that has saved HTML between its delimiters — most core blocks: heading, paragraph, image, group, buttons — that HTML was generated by the editor from those attributes, so changing any attribute other than `metadata` or `lock` this way leaves the block invalid in the editor (a server render_callback does not change that: core/heading has one and is still validated); such ops are refused unless `force: true`, and the right tool is `replace` with the full edited markup. A block whose saved form is empty (self-closing, e.g. `<!-- wp:latest-posts /-->`, `<!-- wp:query /-->`, most Otter blocks) is rendered from its attributes and accepts any declared one), `replace` (swap the block at `path` for the blocks in `content` markup or a registered `pattern_slug`), `insert` (add the blocks from `content`/`pattern_slug`; `at` = `before`|`after` a `path` (default `after`), or `append`|`prepend` to the root list with no `path`), `remove` (delete the block at `path` with its children). Paths are dot-joined zero-based indexes (`0.2.1`) counting addressable blocks only, and every op addresses the tree AS IT IS after the previous ops (an insert shifts later siblings by one). Before anything is saved every block name in new markup must be registered on the server, `set_attributes` keys must exist in the block type\'s attribute schema with matching types, and a pattern must use only registered blocks — otherwise the call fails and the post is untouched. Saves through the same REST route as `wp_update_post`, so `edit_post`, content filtering and revisions apply. Returns { post_id, saved, ops_applied, block_count, warnings, changes }. This is not the synced-pattern tool: to edit a reusable block (wp_block post) use `wp_update_block`.';
    }

    public function get_category() {
        return 'blocks';
    }

    public function get_required_capability() {
        return 'edit_posts';
    }

    public function get_annotations() {
        return array(
            'title'           => $this->get_title(),
            'readOnlyHint'    => false,
            'destructiveHint' => false, 
            'openWorldHint'   => false,
        );
    }

    public function get_input_schema() {
        return array(
            'type'       => 'object',
            'properties' => array(
                'post_id'   => array(
                    'type'        => 'integer',
                    'description' => 'The ID of the post to edit.',
                ),
                'post_type' => array(
                    'type'        => 'string',
                    'description' => 'REST base of the post type (default "posts"; e.g. "pages", "products").',
                    'default'     => 'posts',
                ),
                'ops'       => array(
                    'type'        => 'array',
                    'description' => 'Operations applied in order. Each addresses the tree as left by the previous op.',
                    'items'       => array(
                        'type'       => 'object',
                        'properties' => array(
                            'op'           => array(
                                'type'        => 'string',
                                'description' => 'set_attributes: merge attrs into the block at path. replace: swap the block at path for content/pattern_slug. insert: add content/pattern_slug before/after path, or append/prepend to the root list. remove: delete the block at path.',
                                'enum'        => self::OPS,
                            ),
                            'path'         => array(
                                'type'        => 'string',
                                'description' => 'Dot-joined zero-based path of the target block, e.g. "0.2.1". Required except for insert with at=append|prepend.',
                            ),
                            'attrs'        => array(
                                'type'        => 'object',
                                'description' => 'set_attributes only: attribute name => value to merge (arbitrary keys; null deletes the key). Keys must exist in the block type\'s attribute schema.',
                            ),
                            'content'      => array(
                                'type'        => 'string',
                                'description' => 'replace/insert: Gutenberg block markup (<!-- wp:... -->). One or more root blocks; plain HTML is refused.',
                            ),
                            'pattern_slug' => array(
                                'type'        => 'string',
                                'description' => 'replace/insert: name of a registered block pattern to use instead of content (e.g. "core/query-standard-posts").',
                            ),
                            'at'           => array(
                                'type'        => 'string',
                                'description' => 'insert only: before or after the block at path (default after), or append/prepend to the root list (no path).',
                                'enum'        => self::AT,
                            ),
                            'force'        => array(
                                'type'        => 'boolean',
                                'description' => 'set_attributes only: write rendering attributes into the delimiter of a block that has editor-generated HTML, even though the editor will flag the block as invalid until it is recovered there. Default false (such ops are refused; use replace instead).',
                                'default'     => false,
                            ),
                        ),
                        'required'   => array( 'op' ),
                    ),
                ),
                'dry_run'   => array(
                    'type'        => 'boolean',
                    'description' => 'When true, validate and apply the ops in memory and report the outcome without saving.',
                    'default'     => false,
                ),
            ),
            'required'   => array( 'post_id', 'ops' ),
        );
    }

    public function execute( array $arguments ) {
        $this->validate_required( $arguments, array( 'post_id', 'ops' ) );

        $post_id   = $this->parse_required_id( $arguments['post_id'], 'post_id' );
        $post_type = ! empty( $arguments['post_type'] )
            ? $this->validate_rest_route_segment( $arguments['post_type'], 'post_type' )
            : 'posts';
        $dry_run   = ! empty( $arguments['dry_run'] ) && rest_sanitize_boolean( $arguments['dry_run'] );

        $ops = $this->parse_json_param( $arguments['ops'], 'ops' );
        if ( array() === $ops || array_keys( $ops ) !== range( 0, count( $ops ) - 1 ) ) {
            throw new \InvalidArgumentException( 'ops must be a non-empty array of operation objects.' );
        }

        
        $data = $this->rest_request( 'GET', '/wp/v2/' . $post_type . '/' . $post_id, array( 'context' => 'edit' ) );
        if ( ! isset( $data['content']['raw'] ) ) {
            throw new \RuntimeException( 'The post content could not be read in edit context.' );
        }

        $root = array(
            'blockName'    => null,
            'attrs'        => array(),
            'innerBlocks'  => parse_blocks( (string) $data['content']['raw'] ),
            'innerHTML'    => '',
            'innerContent' => null,
        );

        $warnings = array();
        $changes  = array();
        foreach ( $ops as $i => $op ) {
            if ( ! is_array( $op ) ) {
                throw new \InvalidArgumentException( sprintf( 'ops[%d] must be an object.', $i ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            }
            $changes[] = $this->apply_op( $root, $op, (int) $i, $warnings );
        }

        $content     = serialize_blocks( $root['innerBlocks'] );
        $block_count = count( $this->addressable_indexes( $root['innerBlocks'] ) );

        $result = array(
            'post_id'     => $post_id,
            'saved'       => false,
            'ops_applied' => count( $changes ),
            'block_count' => $block_count,
            'warnings'    => $warnings,
            'changes'     => $changes,
        );

        if ( $dry_run ) {
            $result['dry_run'] = true;
            return $result;
        }

        
        
        
        $saved = $this->rest_request( 'POST', '/wp/v2/' . $post_type . '/' . $post_id, array( 'content' => $content ), 'id,modified' );

        $result['saved']    = true;
        $result['modified'] = isset( $saved['modified'] ) ? $saved['modified'] : '';

        





        do_action( 'easy_mcp_ai_post_blocks_saved', $post_id, $changes );

        return $result;
    }

    









    private function apply_op( array &$root, array $op, $i, array &$warnings ) {
        $type = isset( $op['op'] ) && is_string( $op['op'] ) ? $op['op'] : '';
        if ( ! in_array( $type, self::OPS, true ) ) {
            throw new \InvalidArgumentException(
                sprintf( 'ops[%d]: op must be one of %s.', $i, implode( ', ', self::OPS ) ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            );
        }

        $has_path = isset( $op['path'] ) && '' !== $op['path'];

        if ( 'insert' === $type ) {
            $at = isset( $op['at'] ) && is_string( $op['at'] ) && '' !== $op['at'] ? $op['at'] : 'after';
            if ( ! in_array( $at, self::AT, true ) ) {
                throw new \InvalidArgumentException(
                    sprintf( 'ops[%d]: at must be one of %s.', $i, implode( ', ', self::AT ) ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                );
            }
            $blocks = $this->resolve_op_blocks( $op, $i );
            if ( 'append' === $at || 'prepend' === $at ) {
                if ( $has_path ) {
                    throw new \InvalidArgumentException(
                        sprintf( 'ops[%d]: at=%s inserts into the root list and does not take a path; use before/after with a path to insert next to a block.', $i, $at ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                    );
                }
                $this->root_insert_end( $root, $blocks, 'prepend' === $at );
                return array(
                    'op'       => 'insert',
                    'at'       => $at,
                    'inserted' => $this->names_of( $blocks ),
                );
            }
            if ( ! $has_path ) {
                throw new \InvalidArgumentException( sprintf( 'ops[%d]: insert with at=%s requires a path.', $i, $at ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            }
            $segments   = $this->parse_block_path( $op['path'] );
            $path_label = implode( '.', $segments );
            $container  = &$this->resolve_container( $root, $segments, $path_label );
            $raw        = $this->raw_index_at( $container['innerBlocks'], end( $segments ), $path_label, count( $segments ) - 1 );
            $anchor     = $this->block_display_name( $container['innerBlocks'][ $raw ] );
            $this->container_insert_relative( $container, $raw, $blocks, 'before' === $at );
            return array(
                'op'       => 'insert',
                'at'       => $at,
                'path'     => $path_label,
                'block'    => $anchor,
                'inserted' => $this->names_of( $blocks ),
            );
        }

        if ( ! $has_path ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: %s requires a path.', $i, $type ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }
        $segments   = $this->parse_block_path( $op['path'] );
        $path_label = implode( '.', $segments );
        $container  = &$this->resolve_container( $root, $segments, $path_label );
        $raw        = $this->raw_index_at( $container['innerBlocks'], end( $segments ), $path_label, count( $segments ) - 1 );
        $name       = $this->block_display_name( $container['innerBlocks'][ $raw ] );

        if ( 'remove' === $type ) {
            $this->container_remove( $container, $raw );
            return array( 'op' => 'remove', 'path' => $path_label, 'block' => $name );
        }

        if ( 'replace' === $type ) {
            $blocks = $this->resolve_op_blocks( $op, $i );
            $this->container_replace( $container, $raw, $blocks );
            return array(
                'op'       => 'replace',
                'path'     => $path_label,
                'block'    => $name,
                'inserted' => $this->names_of( $blocks ),
            );
        }

        
        $target = &$container['innerBlocks'][ $raw ];
        if ( empty( $target['blockName'] ) ) {
            throw new \InvalidArgumentException(
                sprintf( 'ops[%d]: the block at path "%s" is classic HTML and has no attributes; use replace.', $i, $path_label ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            );
        }
        if ( ! $this->is_block_type_registered( $name ) ) {
            throw new \InvalidArgumentException(
                sprintf( 'ops[%d]: block type %s at path "%s" is not registered on this server, so its attributes cannot be validated. A block registered only in the editor JavaScript cannot be edited with set_attributes; use replace.', $i, $name, $path_label ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            );
        }
        if ( ! isset( $op['attrs'] ) ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: set_attributes requires attrs.', $i ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }
        $attrs = $this->parse_json_param( $op['attrs'], sprintf( 'ops[%d].attrs', $i ) );
        if ( array() === $attrs ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: attrs must contain at least one key.', $i ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }
        if ( array_keys( $attrs ) === range( 0, count( $attrs ) - 1 ) ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: attrs must be an object of attribute name => value, not a list.', $i ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }

        $schema     = $this->block_attribute_schema( $name );
        $has_markup = $this->block_has_saved_markup( $target );
        $force      = ! empty( $op['force'] ) && rest_sanitize_boolean( $op['force'] );
        if ( ! isset( $target['attrs'] ) || ! is_array( $target['attrs'] ) ) {
            $target['attrs'] = array();
        }
        $set     = array();
        $deleted = array();
        $forced  = array();
        foreach ( $attrs as $key => $value ) {
            $key = (string) $key;
            if ( ! array_key_exists( $key, $schema ) ) {
                $declared = array_keys( $schema );
                throw new \InvalidArgumentException(
                    sprintf(
                        'ops[%d]: attribute "%s" is not declared by block type %s. Declared attributes: %s.',
                        $i,
                        $key, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        $name, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        empty( $declared ) ? '(none)' : implode( ', ', $declared ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                    )
                );
            }
            $decl  = is_array( $schema[ $key ] ) ? $schema[ $key ] : array();
            $types = isset( $decl['type'] ) ? $decl['type'] : null;
            if ( null !== $value && ! $this->attribute_type_matches( $value, $types ) ) {
                throw new \InvalidArgumentException(
                    sprintf(
                        'ops[%d]: attribute "%s" of %s expects type %s, got %s.',
                        $i,
                        $key, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        $name, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        implode( '|', (array) $types ), // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        $this->json_type_label( $value ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                    )
                );
            }
            
            
            
            
            
            
            if ( $has_markup && ! in_array( $key, self::DELIMITER_ONLY_ATTRIBUTES, true ) ) {
                if ( ! $force ) {
                    throw new \InvalidArgumentException(
                        sprintf(
                            'ops[%d]: %s at path "%s" has editor-generated HTML, so changing "%s" in the delimiter alone would leave the block invalid in the editor ("Block contains unexpected or invalid content. Attempt recovery"). Use replace with the full new block markup (read it with wp_get_post_blocks or wp_get_post and edit it), or pass force: true to write the delimiter anyway. Only metadata and lock can be set on such a block without force; a block whose saved form is empty (e.g. <!-- wp:latest-posts /-->) is rendered from its attributes and takes them freely.',
                            $i,
                            $name, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                            $path_label, // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                            $key // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
                        )
                    );
                }
                $forced[] = $key;
            } elseif ( ! $has_markup && null !== $value && ! empty( $decl['source'] ) ) {
                $warnings[] = sprintf(
                    'ops[%d]: attribute "%s" of %s is sourced from the block HTML (source: %s); set_attributes changed only the delimiter JSON, which the editor ignores for this attribute. Use replace with new markup to change it.',
                    $i,
                    $key,
                    $name,
                    (string) $decl['source']
                );
            }
            if ( null === $value ) {
                unset( $target['attrs'][ $key ] );
                $deleted[] = $key;
                continue;
            }
            $target['attrs'][ $key ] = $value;
            $set[]                   = $key;
        }

        if ( ! empty( $forced ) ) {
            $warnings[] = sprintf(
                'ops[%d]: force applied %s to %s at path "%s", which has editor-generated HTML; the editor will flag this block as invalid ("Attempt recovery") until it is recovered there, because its saved HTML no longer matches its attributes.',
                $i,
                implode( ', ', $forced ),
                $name,
                $path_label
            );
        }

        return array(
            'op'      => 'set_attributes',
            'path'    => $path_label,
            'block'   => $name,
            'set'     => $set,
            'deleted' => $deleted,
            'forced'  => $forced,
        );
    }

    







    private function resolve_op_blocks( array $op, $i ) {
        $has_content = isset( $op['content'] ) && is_string( $op['content'] ) && '' !== trim( $op['content'] );
        $has_pattern = isset( $op['pattern_slug'] ) && is_string( $op['pattern_slug'] ) && '' !== trim( $op['pattern_slug'] );

        if ( $has_content && $has_pattern ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: give either content or pattern_slug, not both.', $i ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }
        if ( ! $has_content && ! $has_pattern ) {
            throw new \InvalidArgumentException( sprintf( 'ops[%d]: %s requires content (block markup) or pattern_slug.', $i, $op['op'] ) ); // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
        }

        if ( $has_content ) {
            return $this->parse_markup_for_insert( $op['content'], sprintf( 'ops[%d].content', $i ) );
        }

        $slug = trim( $op['pattern_slug'] );
        if ( ! class_exists( 'WP_Block_Patterns_Registry' ) ) {
            throw new \RuntimeException( 'Block patterns are not available on this WordPress install.' );
        }
        $pattern = \WP_Block_Patterns_Registry::get_instance()->get_registered( $slug );
        if ( ! is_array( $pattern ) || ! isset( $pattern['content'] ) || ! is_string( $pattern['content'] ) ) {
            throw new \InvalidArgumentException(
                sprintf( 'ops[%d]: pattern "%s" is not registered on this site.', $i, $slug ) // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
            );
        }
        return $this->parse_markup_for_insert( $pattern['content'], sprintf( 'ops[%d]: pattern "%s"', $i, $slug ) );
    }

    





    private function names_of( array $blocks ) {
        $names = array();
        foreach ( $blocks as $block ) {
            $names[] = $this->block_display_name( $block );
        }
        return $names;
    }
}
